{"name": "Test Creating A New Task", "status": "broken", "statusDetails": {"message": "TypeError: find_element() takes from 1 to 3 positional arguments but 35 were given", "trace": "setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"81e5f9025ec9f5cc935c7400f3da4a42\")>\n\n    @allure.title(\"Test Creating A New Task\")\n    @allure.severity(allure.severity_level.NORMAL)\n    @pytest.mark.task\n    def test_009_create_task(setup):\n        with allure.step(\"setup driver\"):\n            driver = setup\n            driver.get(Credentials.BASE_URL)\n    \n        # step 1\n        with allure.step('Login to OpenProject'):\n            SharedSteps.login_steps(driver)\n    \n        # step 2\n        with allure.step('Click \"Select a project\" menu button, and select \"TestProject1\" from the drop-down'):\n            SharedSteps.select_project_steps(driver)\n    \n        # step 3\n        with allure.step('On the \"Project Overview\" page, left side menu, click \"Work packages\"'):\n            SharedSteps.goto_work_packages_steps(driver)\n            with allure.step('Note the number of rows displayed in the work packages table'):\n                work_packages_page = WorkPackagesPage(driver)\n                initial_row_count = work_packages_page.count_table_rows()\n    \n        # step 4\n        with allure.step('Click \"+ Create\" green button and select \"TASK\"'):\n            work_packages_page.create_new_task()\n    \n        # step 5\n        with allure.step('Verify the text \"New TASK\" on top of the form that got opened on the right side'):\n            pass\n            # TODO: ASSERT The title of the form is \"New TASK\"\n    \n        # step 6\n        with allure.step('Type unique strings into the subject and description boxes'):\n            work_packages_page.set_task_subject(Credentials.NEW_TASK_SUBJECT)\n            work_packages_page.set_task_description(Credentials.NEW_TASK_DESCRIPTION)\n    \n        # step 7\n        with allure.step('Click \"Save\" button'):\n            work_packages_page.save_new_task()\n            with allure.step('Go back to \"Work Packages\" page'):\n>               work_packages_page.click_go_back_button()\n\ntests\\ui\\test_010_create_task.py:67: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nframework\\pages\\WorkPackagesPage.py:39: in click_go_back_button\n    self.driver_extended.get_element(Locators.btn_back_xpath).click()\ninfra\\web_driver_extensions.py:161: in get_element\n    return self.__get_exists(by, timeout)\ninfra\\web_driver_extensions.py:390: in __get_exists\n    return WebDriverWait(self.driver, timeout, ignored_exceptions).until(ec.presence_of_element_located(by))\nc:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:71: in until\n    value = method(self._driver)\nc:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:64: in __call__\n    return _find_element(driver, self.locator)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"81e5f9025ec9f5cc935c7400f3da4a42\")>, by = \"//*[@id='toolbar']/div/back-button\"\n\n    def _find_element(driver, by):\n        \"\"\"Looks up an element. Logs and re-raises ``WebDriverException``\n        if thrown.\"\"\"\n        try:\n>           return driver.find_element(*by)\nE           TypeError: find_element() takes from 1 to 3 positional arguments but 35 were given\n\nc:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:411: TypeError"}, "steps": [{"name": "setup driver", "status": "passed", "start": 1625152110968, "stop": 1625152112754}, {"name": "Login to OpenProject", "status": "passed", "start": 1625152112754, "stop": 1625152114801}, {"name": "Click \"Select a project\" menu button, and select \"TestProject1\" from the drop-down", "status": "passed", "start": 1625152114801, "stop": 1625152116000}, {"name": "On the \"Project Overview\" page, left side menu, click \"Work packages\"", "status": "passed", "steps": [{"name": "Note the number of rows displayed in the work packages table", "status": "passed", "start": 1625152117006, "stop": 1625152117572}], "start": 1625152116000, "stop": 1625152117572}, {"name": "Click \"+ Create\" green button and select \"TASK\"", "status": "passed", "start": 1625152117572, "stop": 1625152118283}, {"name": "Verify the text \"New TASK\" on top of the form that got opened on the right side", "status": "passed", "start": 1625152118284, "stop": 1625152118284}, {"name": "Type unique strings into the subject and description boxes", "status": "passed", "start": 1625152118284, "stop": 1625152125237}, {"name": "Click \"Save\" button", "status": "broken", "statusDetails": {"message": "TypeError: find_element() takes from 1 to 3 positional arguments but 35 were given\n", "trace": "  File \"D:\\Dev Files\\.John Bryce - Python Automation\\Project\\selenium-test-automation\\tests\\ui\\test_010_create_task.py\", line 67, in test_009_create_task\n    work_packages_page.click_go_back_button()\n  File \"D:\\Dev Files\\.John Bryce - Python Automation\\Project\\selenium-test-automation\\framework\\pages\\WorkPackagesPage.py\", line 39, in click_go_back_button\n    self.driver_extended.get_element(Locators.btn_back_xpath).click()\n  File \"D:\\Dev Files\\.John Bryce - Python Automation\\Project\\selenium-test-automation\\infra\\web_driver_extensions.py\", line 161, in get_element\n    return self.__get_exists(by, timeout)\n  File \"D:\\Dev Files\\.John Bryce - Python Automation\\Project\\selenium-test-automation\\infra\\web_driver_extensions.py\", line 390, in __get_exists\n    return WebDriverWait(self.driver, timeout, ignored_exceptions).until(ec.presence_of_element_located(by))\n  File \"c:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"c:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 64, in __call__\n    return _find_element(driver, self.locator)\n  File \"c:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 411, in _find_element\n    return driver.find_element(*by)\n"}, "steps": [{"name": "Go back to \"Work Packages\" page", "status": "broken", "statusDetails": {"message": "TypeError: find_element() takes from 1 to 3 positional arguments but 35 were given\n", "trace": "  File \"D:\\Dev Files\\.John Bryce - Python Automation\\Project\\selenium-test-automation\\tests\\ui\\test_010_create_task.py\", line 67, in test_009_create_task\n    work_packages_page.click_go_back_button()\n  File \"D:\\Dev Files\\.John Bryce - Python Automation\\Project\\selenium-test-automation\\framework\\pages\\WorkPackagesPage.py\", line 39, in click_go_back_button\n    self.driver_extended.get_element(Locators.btn_back_xpath).click()\n  File \"D:\\Dev Files\\.John Bryce - Python Automation\\Project\\selenium-test-automation\\infra\\web_driver_extensions.py\", line 161, in get_element\n    return self.__get_exists(by, timeout)\n  File \"D:\\Dev Files\\.John Bryce - Python Automation\\Project\\selenium-test-automation\\infra\\web_driver_extensions.py\", line 390, in __get_exists\n    return WebDriverWait(self.driver, timeout, ignored_exceptions).until(ec.presence_of_element_located(by))\n  File \"c:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 71, in until\n    value = method(self._driver)\n  File \"c:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 64, in __call__\n    return _find_element(driver, self.locator)\n  File \"c:\\users\\adele angel\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py\", line 411, in _find_element\n    return driver.find_element(*by)\n"}, "start": 1625152125330, "stop": 1625152125330}], "start": 1625152125237, "stop": 1625152125355}], "start": 1625152110967, "stop": 1625152125356, "uuid": "576de026-d7c6-456d-9421-8eec4d7eb3b8", "historyId": "80fae371a4cadf0893fd497d6153988b", "testCaseId": "eb26ddd98511bb8c7d01092455e6b7bf", "fullName": "tests.ui.test_010_create_task#test_009_create_task", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "task"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_010_create_task"}, {"name": "host", "value": "AdeleAngel"}, {"name": "thread", "value": "21516-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_010_create_task"}]}